;; Copyright (c) 2017 EPITA Research and Development Laboratory
;;
;; Permission is hereby granted, free of charge, to any person obtaining
;; a copy of this software and associated documentation
;; files (the "Software"), to deal in the Software without restriction,
;; including without limitation the rights to use, copy, modify, merge,
;; publish, distribute, sublicense, and/or sell copies of the Software,
;; and to permit persons to whom the Software is furnished to do so,
;; subject to the following conditions:
;;
;; The above copyright notice and this permission notice shall be
;; included in all copies or substantial portions of the Software.
;;
;; THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
;; EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
;; MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
;; NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
;; LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
;; OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
;; WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.



(in-package :lisp-types-test)

(defvar *dnf-true-types*
  '((NOT A)
A
B
(OR A (NOT B) (NOT A))
(NOT B)
(OR (NOT (NOT B)) (NOT (NOT A)) (NOT B) (NOT A))
(NOT (NOT B))
(NOT (NOT A))
(OR (NOT (NOT A)) (NOT B) (NOT A))
(AND B B A (OR A (NOT B) (NOT A)))
(AND A B A (OR A (NOT B) (NOT A)))
(NOT (AND (AND B B A (OR A (NOT B) (NOT A))) (NOT A) B A))
(NOT (AND (AND A B A (OR A (NOT B) (NOT A))) (NOT A) B A))
(NOT (AND (AND (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A))
(NOT (AND (AND (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A))
(NOT (AND (AND B (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A))
(NOT (AND (AND A (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A))
(NOT (AND (AND (NOT B) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A))
(NOT (AND (AND (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A))
(NOT (AND (AND B (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A))
(NOT (AND (AND A (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A))
(NOT (AND (AND (NOT B) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A))
(NOT (AND (AND (NOT A) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A))
(NOT (AND (AND B (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A))
(NOT (AND (AND A (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A))
(NOT (AND (AND (NOT B) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A))
(NOT (AND (AND (NOT A) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A))
(NOT (AND (AND B (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A))
(NOT (AND (AND A (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A))
(NOT (AND (AND (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A))
(NOT (AND (AND (NOT A) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A))
(AND (AND B B A (OR A (NOT B) (NOT A)))
     (OR (NOT (NOT B)) (NOT (NOT A)) (NOT B) (NOT A))
     (OR (NOT (NOT A)) (NOT B) (NOT A)))
(AND (AND A B A (OR A (NOT B) (NOT A)))
     (OR (NOT (NOT B)) (NOT (NOT A)) (NOT B) (NOT A))
     (OR (NOT (NOT A)) (NOT B) (NOT A)))
(NOT C)
C
(NOT D)
D
(AND (NOT C) (NOT D))
T
(AND C D)
(AND C (NOT D))
(AND (NOT C) D)
(NOT E)
E
(AND (NOT C) (NOT E))
(AND C E)
(AND C (NOT E))
(AND (NOT C) E)
(NOT F)
F
(AND (NOT C) (NOT F))
(AND C F)
(AND C (NOT F))
(AND (NOT C) F)
(NOT G)
G
(AND (NOT C) (NOT G))
(AND C G)
(AND C (NOT G))
(AND (NOT C) G)
(AND (NOT D) (NOT C))
(AND D C)
(AND D (NOT C))
(AND (NOT D) C)
(AND (NOT D) (NOT E))
(AND D E)
(AND D (NOT E))
(AND (NOT D) E)
(AND (NOT D) (NOT F))
(AND D F)
(AND D (NOT F))
(AND (NOT D) F)
(AND (NOT D) (NOT G))
(AND D G)
(AND D (NOT G))
(AND (NOT D) G)
(AND (NOT E) (NOT C))
(AND E C)
(AND E (NOT C))
(AND (NOT E) C)
(AND (NOT E) (NOT D))
(AND E D)
(AND E (NOT D))
(AND (NOT E) D)
(AND (NOT E) (NOT F))
(AND E F)
(AND E (NOT F))
(AND (NOT E) F)
(AND (NOT E) (NOT G))
(AND E G)
(AND E (NOT G))
(AND (NOT E) G)
(AND (NOT F) (NOT C))
(AND F C)
(AND F (NOT C))
(AND (NOT F) C)
(AND (NOT F) (NOT D))
(AND F D)
(AND F (NOT D))
(AND (NOT F) D)
(AND (NOT F) (NOT E))
(AND F E)
(AND F (NOT E))
(AND (NOT F) E)
(AND (NOT F) (NOT G))
(AND F G)
(AND F (NOT G))
(AND (NOT F) G)
(AND (NOT G) (NOT C))
(AND G C)
(AND G (NOT C))
(AND (NOT G) C)
(AND (NOT G) (NOT D))
(AND G D)
(AND G (NOT D))
(AND (NOT G) D)
(AND (NOT G) (NOT E))
(AND G E)
(AND G (NOT E))
(AND (NOT G) E)
(AND (NOT G) (NOT F))
(AND G F)
(AND G (NOT F))
(AND (NOT G) F)
(AND A (NOT G))
(AND A G)
(AND (NOT G) A)
(AND G A)
(AND (NOT C) (NOT A))
(AND C A)
(AND C (NOT A))
(AND (NOT C) A)
(AND (NOT D) (NOT A))
(AND D A)
(AND D (NOT A))
(AND (NOT D) A)
(AND (NOT A) (NOT C))
(AND A C)
(AND A (NOT C))
(AND (NOT A) C)
(AND (NOT A) (NOT D))
(AND A D)
(AND A (NOT D))
(AND (NOT A) D)
(AND (NOT A) (NOT F))
(AND A F)
(AND A (NOT F))
(AND (NOT A) F)
(AND (NOT F) (NOT A))
(AND F A)
(AND F (NOT A))
(AND (NOT F) A)
(NOT H)
H
(AND A (NOT H))
(AND (NOT H) A)
(AND A H)
(AND (NOT H) (NOT G))
(AND (NOT G) (NOT H))
(AND H (NOT G))
(AND H G)
(AND (NOT G) H)
(AND G H)
(AND (NOT A) (NOT C) (NOT D) (NOT F))
(AND (NOT C) (NOT D) (NOT A) (NOT F))
(AND (NOT D) (NOT A) (NOT F))
(AND (NOT C) (NOT A) (NOT F))
(AND (NOT C) (NOT D) (NOT A))
I
(AND I (NOT D))
(AND I D)
(AND (NOT D) I)
(AND D I)
(NOT I)
(AND C (NOT I))
(AND C I)
(AND (NOT A) (NOT I))
(AND A I)
(AND A (NOT I))
(AND (NOT A) I)
(AND (NOT I) (NOT A))
(AND I A)
(AND I (NOT A))
(AND (NOT I) A)
(AND (NOT I) (NOT D))
(AND (NOT I) D)
(AND (NOT I) (NOT F))
(AND I F)
(AND I (NOT F))
(AND (NOT I) F)
(AND (NOT D) (NOT I))
(AND D (NOT I))
(AND (NOT F) (NOT I))
(AND F I)
(AND F (NOT I))
(AND (NOT F) I)
(AND (NOT A) (NOT I) (NOT D) (NOT F))
(AND (NOT D) (NOT A) (NOT F) (NOT I))
(AND (NOT A) (NOT F) (NOT I))
(AND (NOT D) (NOT A) (NOT I))
(AND I (NOT C))
(AND I C)
(AND (NOT C) I)
))


(defvar *dnf-false-types*
  '((AND (AND A (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
(AND A (NOT A) B A (OR A (NOT B) (NOT A)))
(AND (AND (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
(AND (NOT B) (NOT A) B A (OR A (NOT B) (NOT A)))
(AND (AND (NOT A) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
(AND (NOT A) (NOT A) B A (OR A (NOT B) (NOT A)))
(AND
 (AND (AND (NOT A) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A)))
      (OR (NOT (NOT B)) (NOT (NOT A)) (NOT B) (NOT A))
      (OR (NOT (NOT A)) (NOT B) (NOT A)))
 (OR (AND (AND B B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND A B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND B (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND A (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT B) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND B (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND A (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT B) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT A) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND B (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND A (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT B) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT A) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND B (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND A (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT A) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)))
(AND (AND (NOT A) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A)))
     (OR (NOT (NOT B)) (NOT (NOT A)) (NOT B) (NOT A))
     (OR (NOT (NOT A)) (NOT B) (NOT A)))
(AND (NOT A) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A)))
(OR (AND (AND B B A (OR A (NOT B) (NOT A))) (NOT A) B A)
    (AND (AND A B A (OR A (NOT B) (NOT A))) (NOT A) B A)
    (AND (AND (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
    (AND (AND (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
    (AND (AND B (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
    (AND (AND A (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
    (AND (AND (NOT B) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
    (AND (AND (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
    (AND (AND B (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
    (AND (AND A (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
    (AND (AND (NOT B) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
    (AND (AND (NOT A) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
    (AND (AND B (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
    (AND (AND A (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
    (AND (AND (NOT B) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
    (AND (AND (NOT A) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
    (AND (AND B (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
    (AND (AND A (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
    (AND (AND (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
    (AND (AND (NOT A) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A))
(AND (AND B B A (OR A (NOT B) (NOT A))) (NOT A) B A)
(AND (AND A B A (OR A (NOT B) (NOT A))) (NOT A) B A)
(AND (AND (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
(AND (NOT B) B A (OR A (NOT B) (NOT A)))
(AND (AND (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
(AND (NOT A) B A (OR A (NOT B) (NOT A)))
(AND (AND B (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
(AND B (NOT B) B A (OR A (NOT B) (NOT A)))
(AND (AND A (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
(AND A (NOT B) B A (OR A (NOT B) (NOT A)))
(AND (AND (NOT B) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
(AND (NOT B) (NOT B) B A (OR A (NOT B) (NOT A)))
(AND (AND (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
(AND (NOT A) (NOT B) B A (OR A (NOT B) (NOT A)))
(AND (AND B (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
(AND B (NOT A) (NOT B) B A (OR A (NOT B) (NOT A)))
(AND (AND A (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
(AND A (NOT A) (NOT B) B A (OR A (NOT B) (NOT A)))
(AND (AND (NOT B) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
(AND (NOT B) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A)))
(AND (AND (NOT A) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
(AND (NOT A) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A)))
(AND (AND B (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
(AND B (NOT B) (NOT A) B A (OR A (NOT B) (NOT A)))
(AND (AND A (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
(AND A (NOT B) (NOT A) B A (OR A (NOT B) (NOT A)))
(AND (AND (NOT B) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
(AND (NOT B) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A)))
(AND (AND (NOT A) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
(AND (AND B (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
(AND B (NOT A) B A (OR A (NOT B) (NOT A)))
(AND
 (AND (AND B (NOT A) B A (OR A (NOT B) (NOT A)))
      (OR (NOT (NOT B)) (NOT (NOT A)) (NOT B) (NOT A))
      (OR (NOT (NOT A)) (NOT B) (NOT A)))
 (OR (AND (AND B B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND A B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND B (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND A (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT B) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND B (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND A (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT B) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT A) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND B (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND A (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT B) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT A) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND B (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND A (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT A) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)))
(AND (AND B (NOT A) B A (OR A (NOT B) (NOT A)))
     (OR (NOT (NOT B)) (NOT (NOT A)) (NOT B) (NOT A))
     (OR (NOT (NOT A)) (NOT B) (NOT A)))
(AND
 (AND (AND A (NOT A) B A (OR A (NOT B) (NOT A)))
      (OR (NOT (NOT B)) (NOT (NOT A)) (NOT B) (NOT A))
      (OR (NOT (NOT A)) (NOT B) (NOT A)))
 (OR (AND (AND B B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND A B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND B (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND A (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT B) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND B (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND A (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT B) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT A) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND B (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND A (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT B) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT A) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND B (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND A (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT A) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)))
(AND (AND A (NOT A) B A (OR A (NOT B) (NOT A)))
     (OR (NOT (NOT B)) (NOT (NOT A)) (NOT B) (NOT A))
     (OR (NOT (NOT A)) (NOT B) (NOT A)))
(AND
 (AND (AND (NOT B) (NOT A) B A (OR A (NOT B) (NOT A)))
      (OR (NOT (NOT B)) (NOT (NOT A)) (NOT B) (NOT A))
      (OR (NOT (NOT A)) (NOT B) (NOT A)))
 (OR (AND (AND B B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND A B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND B (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND A (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT B) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND B (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND A (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT B) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT A) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND B (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND A (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT B) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT A) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND B (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND A (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT A) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)))
(AND (AND (NOT B) (NOT A) B A (OR A (NOT B) (NOT A)))
     (OR (NOT (NOT B)) (NOT (NOT A)) (NOT B) (NOT A))
     (OR (NOT (NOT A)) (NOT B) (NOT A)))
(AND
 (AND (AND (NOT A) (NOT A) B A (OR A (NOT B) (NOT A)))
      (OR (NOT (NOT B)) (NOT (NOT A)) (NOT B) (NOT A))
      (OR (NOT (NOT A)) (NOT B) (NOT A)))
 (OR (AND (AND B B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND A B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND B (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND A (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT B) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND B (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND A (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT B) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT A) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND B (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND A (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT B) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT A) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND B (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND A (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT A) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)))
(AND (AND (NOT A) (NOT A) B A (OR A (NOT B) (NOT A)))
     (OR (NOT (NOT B)) (NOT (NOT A)) (NOT B) (NOT A))
     (OR (NOT (NOT A)) (NOT B) (NOT A)))
(AND
 (AND
  (AND (AND (NOT A) B A (OR A (NOT B) (NOT A)))
       (OR (NOT (NOT B)) (NOT (NOT A)) (NOT B) (NOT A))
       (OR (NOT (NOT A)) (NOT B) (NOT A)))
  (NOT (AND (AND B B A (OR A (NOT B) (NOT A))) (NOT A) B A))
  (NOT (AND (AND A B A (OR A (NOT B) (NOT A))) (NOT A) B A))
  (NOT (AND (AND (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A))
  (NOT (AND (AND (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A))
  (NOT (AND (AND B (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A))
  (NOT (AND (AND A (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A))
  (NOT (AND (AND (NOT B) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A))
  (NOT (AND (AND (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A))
  (NOT (AND (AND B (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A))
  (NOT (AND (AND A (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A))
  (NOT
   (AND (AND (NOT B) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A))
  (NOT
   (AND (AND (NOT A) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A))
  (NOT (AND (AND B (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A))
  (NOT (AND (AND A (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A))
  (NOT
   (AND (AND (NOT B) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A))
  (NOT
   (AND (AND (NOT A) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A))
  (NOT (AND (AND B (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A))
  (NOT (AND (AND A (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A))
  (NOT (AND (AND (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A))
  (NOT (AND (AND (NOT A) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)))
 (OR
  (AND
   (AND (AND B B A (OR A (NOT B) (NOT A)))
        (OR (NOT (NOT B)) (NOT (NOT A)) (NOT B) (NOT A))
        (OR (NOT (NOT A)) (NOT B) (NOT A)))
   (OR (AND (AND B B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND B (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND B (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND (NOT A) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND B (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND (NOT A) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND B (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT A) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)))
  (AND
   (AND (AND A B A (OR A (NOT B) (NOT A)))
        (OR (NOT (NOT B)) (NOT (NOT A)) (NOT B) (NOT A))
        (OR (NOT (NOT A)) (NOT B) (NOT A)))
   (OR (AND (AND B B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND B (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND B (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND (NOT A) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND B (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND (NOT A) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND B (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT A) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)))
  (AND
   (AND (AND (NOT B) B A (OR A (NOT B) (NOT A)))
        (OR (NOT (NOT B)) (NOT (NOT A)) (NOT B) (NOT A))
        (OR (NOT (NOT A)) (NOT B) (NOT A)))
   (OR (AND (AND B B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND B (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND B (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND (NOT A) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND B (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND (NOT A) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND B (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT A) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)))
  (AND
   (AND (AND (NOT A) B A (OR A (NOT B) (NOT A)))
        (OR (NOT (NOT B)) (NOT (NOT A)) (NOT B) (NOT A))
        (OR (NOT (NOT A)) (NOT B) (NOT A)))
   (OR (AND (AND B B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND B (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND B (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND (NOT A) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND B (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND (NOT A) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND B (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT A) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)))
  (AND
   (AND (AND B (NOT B) B A (OR A (NOT B) (NOT A)))
        (OR (NOT (NOT B)) (NOT (NOT A)) (NOT B) (NOT A))
        (OR (NOT (NOT A)) (NOT B) (NOT A)))
   (OR (AND (AND B B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND B (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND B (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND (NOT A) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND B (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND (NOT A) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND B (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT A) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)))
  (AND
   (AND (AND A (NOT B) B A (OR A (NOT B) (NOT A)))
        (OR (NOT (NOT B)) (NOT (NOT A)) (NOT B) (NOT A))
        (OR (NOT (NOT A)) (NOT B) (NOT A)))
   (OR (AND (AND B B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND B (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND B (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND (NOT A) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND B (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND (NOT A) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND B (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT A) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)))
  (AND
   (AND (AND (NOT B) (NOT B) B A (OR A (NOT B) (NOT A)))
        (OR (NOT (NOT B)) (NOT (NOT A)) (NOT B) (NOT A))
        (OR (NOT (NOT A)) (NOT B) (NOT A)))
   (OR (AND (AND B B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND B (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND B (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND (NOT A) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND B (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND (NOT A) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND B (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT A) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)))
  (AND
   (AND (AND (NOT A) (NOT B) B A (OR A (NOT B) (NOT A)))
        (OR (NOT (NOT B)) (NOT (NOT A)) (NOT B) (NOT A))
        (OR (NOT (NOT A)) (NOT B) (NOT A)))
   (OR (AND (AND B B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND B (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND B (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND (NOT A) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND B (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND (NOT A) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND B (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT A) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)))
  (AND
   (AND (AND B (NOT A) (NOT B) B A (OR A (NOT B) (NOT A)))
        (OR (NOT (NOT B)) (NOT (NOT A)) (NOT B) (NOT A))
        (OR (NOT (NOT A)) (NOT B) (NOT A)))
   (OR (AND (AND B B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND B (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND B (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND (NOT A) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND B (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND (NOT A) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND B (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT A) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)))
  (AND
   (AND (AND A (NOT A) (NOT B) B A (OR A (NOT B) (NOT A)))
        (OR (NOT (NOT B)) (NOT (NOT A)) (NOT B) (NOT A))
        (OR (NOT (NOT A)) (NOT B) (NOT A)))
   (OR (AND (AND B B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND B (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND B (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND (NOT A) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND B (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND (NOT A) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND B (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT A) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)))
  (AND
   (AND (AND (NOT B) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A)))
        (OR (NOT (NOT B)) (NOT (NOT A)) (NOT B) (NOT A))
        (OR (NOT (NOT A)) (NOT B) (NOT A)))
   (OR (AND (AND B B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND B (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND B (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND (NOT A) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND B (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND (NOT A) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND B (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT A) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)))
  (AND
   (AND (AND (NOT A) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A)))
        (OR (NOT (NOT B)) (NOT (NOT A)) (NOT B) (NOT A))
        (OR (NOT (NOT A)) (NOT B) (NOT A)))
   (OR (AND (AND B B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND B (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND B (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND (NOT A) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND B (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND (NOT A) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND B (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT A) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)))
  (AND
   (AND (AND B (NOT B) (NOT A) B A (OR A (NOT B) (NOT A)))
        (OR (NOT (NOT B)) (NOT (NOT A)) (NOT B) (NOT A))
        (OR (NOT (NOT A)) (NOT B) (NOT A)))
   (OR (AND (AND B B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND B (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND B (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND (NOT A) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND B (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND (NOT A) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND B (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT A) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)))
  (AND
   (AND (AND A (NOT B) (NOT A) B A (OR A (NOT B) (NOT A)))
        (OR (NOT (NOT B)) (NOT (NOT A)) (NOT B) (NOT A))
        (OR (NOT (NOT A)) (NOT B) (NOT A)))
   (OR (AND (AND B B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND B (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND B (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND (NOT A) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND B (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND (NOT A) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND B (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT A) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)))
  (AND
   (AND (AND (NOT B) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A)))
        (OR (NOT (NOT B)) (NOT (NOT A)) (NOT B) (NOT A))
        (OR (NOT (NOT A)) (NOT B) (NOT A)))
   (OR (AND (AND B B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND B (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND B (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND (NOT A) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND B (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND (NOT A) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND B (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT A) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)))
  (AND
   (AND (AND (NOT A) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A)))
        (OR (NOT (NOT B)) (NOT (NOT A)) (NOT B) (NOT A))
        (OR (NOT (NOT A)) (NOT B) (NOT A)))
   (OR (AND (AND B B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND B (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND B (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND (NOT A) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND B (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND (NOT A) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND B (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT A) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)))
  (AND
   (AND (AND B (NOT A) B A (OR A (NOT B) (NOT A)))
        (OR (NOT (NOT B)) (NOT (NOT A)) (NOT B) (NOT A))
        (OR (NOT (NOT A)) (NOT B) (NOT A)))
   (OR (AND (AND B B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND B (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND B (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND (NOT A) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND B (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND (NOT A) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND B (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT A) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)))
  (AND
   (AND (AND A (NOT A) B A (OR A (NOT B) (NOT A)))
        (OR (NOT (NOT B)) (NOT (NOT A)) (NOT B) (NOT A))
        (OR (NOT (NOT A)) (NOT B) (NOT A)))
   (OR (AND (AND B B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND B (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND B (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND (NOT A) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND B (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND (NOT A) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND B (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT A) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)))
  (AND
   (AND (AND (NOT B) (NOT A) B A (OR A (NOT B) (NOT A)))
        (OR (NOT (NOT B)) (NOT (NOT A)) (NOT B) (NOT A))
        (OR (NOT (NOT A)) (NOT B) (NOT A)))
   (OR (AND (AND B B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND B (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND B (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND (NOT A) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND B (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND (NOT A) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND B (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT A) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)))
  (AND
   (AND (AND (NOT A) (NOT A) B A (OR A (NOT B) (NOT A)))
        (OR (NOT (NOT B)) (NOT (NOT A)) (NOT B) (NOT A))
        (OR (NOT (NOT A)) (NOT B) (NOT A)))
   (OR (AND (AND B B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND B (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND B (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND (NOT A) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND B (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND (NOT A) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
            A)
       (AND (AND B (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND A (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
       (AND (AND (NOT A) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)))))
(AND
 (AND (AND (NOT A) B A (OR A (NOT B) (NOT A)))
      (OR (NOT (NOT B)) (NOT (NOT A)) (NOT B) (NOT A))
      (OR (NOT (NOT A)) (NOT B) (NOT A)))
 (NOT (AND (AND B B A (OR A (NOT B) (NOT A))) (NOT A) B A))
 (NOT (AND (AND A B A (OR A (NOT B) (NOT A))) (NOT A) B A))
 (NOT (AND (AND (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A))
 (NOT (AND (AND (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A))
 (NOT (AND (AND B (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A))
 (NOT (AND (AND A (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A))
 (NOT (AND (AND (NOT B) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A))
 (NOT (AND (AND (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A))
 (NOT (AND (AND B (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A))
 (NOT (AND (AND A (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A))
 (NOT
  (AND (AND (NOT B) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A))
 (NOT
  (AND (AND (NOT A) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A))
 (NOT (AND (AND B (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A))
 (NOT (AND (AND A (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A))
 (NOT
  (AND (AND (NOT B) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A))
 (NOT
  (AND (AND (NOT A) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A))
 (NOT (AND (AND B (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A))
 (NOT (AND (AND A (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A))
 (NOT (AND (AND (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A))
 (NOT (AND (AND (NOT A) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)))
(AND (AND (NOT A) B A (OR A (NOT B) (NOT A)))
     (OR (NOT (NOT B)) (NOT (NOT A)) (NOT B) (NOT A))
     (OR (NOT (NOT A)) (NOT B) (NOT A)))
(OR
 (AND
  (AND (AND B B A (OR A (NOT B) (NOT A)))
       (OR (NOT (NOT B)) (NOT (NOT A)) (NOT B) (NOT A))
       (OR (NOT (NOT A)) (NOT B) (NOT A)))
  (OR (AND (AND B B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND B (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND B (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND (NOT A) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND B (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND (NOT A) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND B (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT A) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)))
 (AND
  (AND (AND A B A (OR A (NOT B) (NOT A)))
       (OR (NOT (NOT B)) (NOT (NOT A)) (NOT B) (NOT A))
       (OR (NOT (NOT A)) (NOT B) (NOT A)))
  (OR (AND (AND B B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND B (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND B (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND (NOT A) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND B (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND (NOT A) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND B (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT A) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)))
 (AND
  (AND (AND (NOT B) B A (OR A (NOT B) (NOT A)))
       (OR (NOT (NOT B)) (NOT (NOT A)) (NOT B) (NOT A))
       (OR (NOT (NOT A)) (NOT B) (NOT A)))
  (OR (AND (AND B B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND B (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND B (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND (NOT A) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND B (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND (NOT A) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND B (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT A) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)))
 (AND
  (AND (AND (NOT A) B A (OR A (NOT B) (NOT A)))
       (OR (NOT (NOT B)) (NOT (NOT A)) (NOT B) (NOT A))
       (OR (NOT (NOT A)) (NOT B) (NOT A)))
  (OR (AND (AND B B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND B (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND B (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND (NOT A) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND B (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND (NOT A) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND B (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT A) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)))
 (AND
  (AND (AND B (NOT B) B A (OR A (NOT B) (NOT A)))
       (OR (NOT (NOT B)) (NOT (NOT A)) (NOT B) (NOT A))
       (OR (NOT (NOT A)) (NOT B) (NOT A)))
  (OR (AND (AND B B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND B (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND B (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND (NOT A) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND B (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND (NOT A) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND B (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT A) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)))
 (AND
  (AND (AND A (NOT B) B A (OR A (NOT B) (NOT A)))
       (OR (NOT (NOT B)) (NOT (NOT A)) (NOT B) (NOT A))
       (OR (NOT (NOT A)) (NOT B) (NOT A)))
  (OR (AND (AND B B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND B (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND B (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND (NOT A) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND B (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND (NOT A) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND B (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT A) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)))
 (AND
  (AND (AND (NOT B) (NOT B) B A (OR A (NOT B) (NOT A)))
       (OR (NOT (NOT B)) (NOT (NOT A)) (NOT B) (NOT A))
       (OR (NOT (NOT A)) (NOT B) (NOT A)))
  (OR (AND (AND B B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND B (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND B (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND (NOT A) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND B (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND (NOT A) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND B (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT A) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)))
 (AND
  (AND (AND (NOT A) (NOT B) B A (OR A (NOT B) (NOT A)))
       (OR (NOT (NOT B)) (NOT (NOT A)) (NOT B) (NOT A))
       (OR (NOT (NOT A)) (NOT B) (NOT A)))
  (OR (AND (AND B B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND B (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND B (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND (NOT A) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND B (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND (NOT A) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND B (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT A) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)))
 (AND
  (AND (AND B (NOT A) (NOT B) B A (OR A (NOT B) (NOT A)))
       (OR (NOT (NOT B)) (NOT (NOT A)) (NOT B) (NOT A))
       (OR (NOT (NOT A)) (NOT B) (NOT A)))
  (OR (AND (AND B B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND B (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND B (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND (NOT A) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND B (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND (NOT A) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND B (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT A) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)))
 (AND
  (AND (AND A (NOT A) (NOT B) B A (OR A (NOT B) (NOT A)))
       (OR (NOT (NOT B)) (NOT (NOT A)) (NOT B) (NOT A))
       (OR (NOT (NOT A)) (NOT B) (NOT A)))
  (OR (AND (AND B B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND B (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND B (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND (NOT A) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND B (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND (NOT A) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND B (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT A) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)))
 (AND
  (AND (AND (NOT B) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A)))
       (OR (NOT (NOT B)) (NOT (NOT A)) (NOT B) (NOT A))
       (OR (NOT (NOT A)) (NOT B) (NOT A)))
  (OR (AND (AND B B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND B (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND B (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND (NOT A) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND B (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND (NOT A) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND B (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT A) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)))
 (AND
  (AND (AND (NOT A) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A)))
       (OR (NOT (NOT B)) (NOT (NOT A)) (NOT B) (NOT A))
       (OR (NOT (NOT A)) (NOT B) (NOT A)))
  (OR (AND (AND B B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND B (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND B (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND (NOT A) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND B (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND (NOT A) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND B (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT A) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)))
 (AND
  (AND (AND B (NOT B) (NOT A) B A (OR A (NOT B) (NOT A)))
       (OR (NOT (NOT B)) (NOT (NOT A)) (NOT B) (NOT A))
       (OR (NOT (NOT A)) (NOT B) (NOT A)))
  (OR (AND (AND B B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND B (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND B (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND (NOT A) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND B (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND (NOT A) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND B (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT A) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)))
 (AND
  (AND (AND A (NOT B) (NOT A) B A (OR A (NOT B) (NOT A)))
       (OR (NOT (NOT B)) (NOT (NOT A)) (NOT B) (NOT A))
       (OR (NOT (NOT A)) (NOT B) (NOT A)))
  (OR (AND (AND B B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND B (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND B (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND (NOT A) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND B (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND (NOT A) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND B (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT A) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)))
 (AND
  (AND (AND (NOT B) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A)))
       (OR (NOT (NOT B)) (NOT (NOT A)) (NOT B) (NOT A))
       (OR (NOT (NOT A)) (NOT B) (NOT A)))
  (OR (AND (AND B B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND B (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND B (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND (NOT A) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND B (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND (NOT A) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND B (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT A) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)))
 (AND
  (AND (AND (NOT A) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A)))
       (OR (NOT (NOT B)) (NOT (NOT A)) (NOT B) (NOT A))
       (OR (NOT (NOT A)) (NOT B) (NOT A)))
  (OR (AND (AND B B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND B (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND B (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND (NOT A) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND B (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND (NOT A) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND B (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT A) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)))
 (AND
  (AND (AND B (NOT A) B A (OR A (NOT B) (NOT A)))
       (OR (NOT (NOT B)) (NOT (NOT A)) (NOT B) (NOT A))
       (OR (NOT (NOT A)) (NOT B) (NOT A)))
  (OR (AND (AND B B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND B (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND B (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND (NOT A) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND B (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND (NOT A) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND B (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT A) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)))
 (AND
  (AND (AND A (NOT A) B A (OR A (NOT B) (NOT A)))
       (OR (NOT (NOT B)) (NOT (NOT A)) (NOT B) (NOT A))
       (OR (NOT (NOT A)) (NOT B) (NOT A)))
  (OR (AND (AND B B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND B (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND B (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND (NOT A) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND B (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND (NOT A) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND B (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT A) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)))
 (AND
  (AND (AND (NOT B) (NOT A) B A (OR A (NOT B) (NOT A)))
       (OR (NOT (NOT B)) (NOT (NOT A)) (NOT B) (NOT A))
       (OR (NOT (NOT A)) (NOT B) (NOT A)))
  (OR (AND (AND B B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND B (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND B (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND (NOT A) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND B (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND (NOT A) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND B (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT A) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)))
 (AND
  (AND (AND (NOT A) (NOT A) B A (OR A (NOT B) (NOT A)))
       (OR (NOT (NOT B)) (NOT (NOT A)) (NOT B) (NOT A))
       (OR (NOT (NOT A)) (NOT B) (NOT A)))
  (OR (AND (AND B B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND B (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND B (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND (NOT A) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND B (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND (NOT A) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B
           A)
      (AND (AND B (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND A (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
      (AND (AND (NOT A) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A))))
(AND
 (AND (AND B B A (OR A (NOT B) (NOT A)))
      (OR (NOT (NOT B)) (NOT (NOT A)) (NOT B) (NOT A))
      (OR (NOT (NOT A)) (NOT B) (NOT A)))
 (OR (AND (AND B B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND A B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND B (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND A (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT B) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND B (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND A (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT B) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT A) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND B (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND A (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT B) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT A) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND B (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND A (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT A) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)))
(AND
 (AND (AND A B A (OR A (NOT B) (NOT A)))
      (OR (NOT (NOT B)) (NOT (NOT A)) (NOT B) (NOT A))
      (OR (NOT (NOT A)) (NOT B) (NOT A)))
 (OR (AND (AND B B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND A B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND B (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND A (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT B) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND B (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND A (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT B) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT A) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND B (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND A (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT B) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT A) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND B (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND A (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT A) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)))
(AND
 (AND (AND (NOT B) B A (OR A (NOT B) (NOT A)))
      (OR (NOT (NOT B)) (NOT (NOT A)) (NOT B) (NOT A))
      (OR (NOT (NOT A)) (NOT B) (NOT A)))
 (OR (AND (AND B B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND A B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND B (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND A (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT B) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND B (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND A (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT B) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT A) (NOT A) (NOT B) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND B (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND A (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT B) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT A) (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND B (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND A (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT B) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)
     (AND (AND (NOT A) (NOT A) B A (OR A (NOT B) (NOT A))) (NOT A) B A)))
(AND (AND (NOT B) B A (OR A (NOT B) (NOT A)))
     (OR (NOT (NOT B)) (NOT (NOT A)) (NOT B) (NOT A))
     (OR (NOT (NOT A)) (NOT B) (NOT A)))
NIL
))


(define-test test-dnf/test-true
  (dolist (true-type *dnf-true-types*)
    (assert-true (type-to-dnf true-type))))

(define-test test-dnf/test-false
  (dolist (false-type *dnf-false-types*)
    (assert-false (type-to-dnf false-type))))


(define-test test-dnf/test1
  (assert-true (dnf-type-p (type-to-dnf '(AND
                                          (NOT FLOAT)
                                          (NOT UNSIGNED-BYTE)
                                          (NOT TEST-ARRAY-RANK)
                                          REAL
                                          (NOT FLOAT)
                                          (NOT TEST-ARRAY-RANK)
                                          TEST-FLOAT-DIGITS)))))

(define-test test/remove-supers-2
  (assert-true (equal '(vector)
		      (remove-supers '(sequence array vector))))
  (assert-true (equal '(sequence array)
		      (remove-subs '(sequence array vector)))))

(define-test test/remove-supers
  (assert-true (equal '(number string list)
		      (remove-supers '(number string list))))
  (assert-true (equal '(number string null)
		      (remove-supers '(number string null list))))
  (assert-true (equal '(number string null)
		      (remove-supers '(number string list null))))
  (assert-true (equal '(number string null)
		      (remove-supers '(number list string null))))
  (assert-true (equal '(number string null)
		      (remove-supers '(list number string null))))
  (assert-true (equal '(number)
		      (remove-supers '(number number))))
  (assert-true (equal '(number)
		      (remove-supers '(number (not array)))))
  (assert-true (equal '(number)
		      (remove-supers '((not array) number)))))

(define-test test/remove-subs
  (assert-true (equal '(number string list)
		      (remove-subs '(number string list))))
  (assert-true (equal '(number string list)
		      (remove-subs '(number string null list))))
  (assert-true (equal '(number string list)
		      (remove-subs '(number string list null))))
  (assert-true (equal '(number list string)
		      (remove-subs '(number list string null))))
  (assert-true (equal '(list number string)
		      (remove-subs '(list number string null))))
  (assert-true (equal '(number)
		      (remove-subs '(number number))))
  (assert-true (equal '((not array))
		      (remove-subs '(number (not array)))))
  (assert-true (equal '((not array))
		      (remove-subs '((not array) number)))))
